# Generated by Django 4.1.7 on 2023-05-08 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('last_edited', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Edited')),
            ],
            options={
                'ordering': ['last_edited'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=50, verbose_name='Preferred Name')),
                ('role', models.CharField(max_length=30)),
                ('profile', models.TextField()),
                ('last_edited', models.DateField(auto_now=True, verbose_name='Last Edited')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_candidates', to='resume.candidate')),
            ],
            options={
                'ordering': ['preferred_name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('use_case', models.TextField(verbose_name='Use case')),
                ('last_edited', models.DateField(auto_now=True, verbose_name='Last Edited')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_candidates', to='resume.candidate')),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.BigIntegerField()),
                ('candidate_professional_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.candidateprofessionalexperience')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('order', 'candidate_professional_experience')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.BigIntegerField()),
                ('candidate_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.candidateinfo')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('order', 'candidate_info')},
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.BigIntegerField()),
                ('candidate_professional_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='resume.candidateprofessionalexperience')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('order', 'candidate_professional_experience')},
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.BigIntegerField()),
                ('candidate_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume.candidateinfo')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('order', 'candidate_info')},
            },
        ),
    ]
