name: 'Unittest and Linting'
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-20.04

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.2'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.txt
      - name: Run pytest
        run: |
          # "pkg_resources is deprecated as an API"
          # https://stackoverflow.com/questions/76043689/pkg-resources-is-deprecated-as-an-api
          pytest -W ignore::DeprecationWarning

      - name: Run flake8
        run: |
          flake8

      - name: Run pylint
        run: |
          pylint --load-plugins pylint_django --django-settings-module=resume_generator_api.settings **/*.py
